version: '3'
services:
  mkvtoolnix:
    image: jlesage/mkvtoolnix:latest
    ports:
      - "192.168.0.208:5802:5800"
    #environment:
      #- UID = 1041
      #- GID = 1040
    volumes:
      - "/home/atort88/docker/mkvtoolnix:/config:rw"
      - "/media/plex_nas:/storage:rw"
    restart: unless-stopped
