version: '3'
services:
  filebot:
    image: jlesage/filebot
    #env_file:
      #- path: /home/atort88/docker/.env
    ports:
      #- "${HOSTIP}:5801:5800"
      - "192.168.0.208:5801:5800"
    environment:
      #- DARK_MODE = 1
      #- WEB_LISTENING_PORT = 5801
      - UID = 1041
      - GID = 1040
    volumes:
      - "/home/atort88/docker/filebot:/config:rw"
      - "/media/plex_nas/:/plex:rw"
      #- "/media/plexA/:/TV_Storage:rw"
      #- "/media/plexB/:/Film_Storage:rw"
      #- "/media/plexB/Films:/Film_Storage:rw"
      #- "/home/atort88/qbittorrent/downloads/tv:/TV_Downloads:rw"
      #- "/home/atort88/qbittorrent/downloads/films:/Film_Downloads:rw"
      ###NEED TO UPDATE PLEX ON CONTAINER FOR THIS
    restart: unless-stopped
#AMC_INTERVAL	Time (in seconds) between each invocation of the Automated Media Center (AMC) script.	1800
#AMC_INPUT_STABLE_TIME	Time (in seconds) during which properties (e.g. size, time, etc) of files in the watch folder need to remain the same before invoking the Automated Media Center (AMC) script. This is to avoid processing the watch folder while files are being copied.	10
#AMC_ACTION	Action performed by the Automated Media Center (AMC) script on files. Valid values are test, copy, move, symlink, hardlink, keeplink, duplicate or clone. Use the test operation to perform a dry-run and verify that everything gets matched up correctly.	test
#AMC_CONFLICT	Conflict resolution strategy used by the Automated Media Center (AMC) script. When set to skip, existing files are never overriden, while auto overrides existing file only if new media is better.	auto
#AMC_MATCH_MODE	Match mode used by the Automated Media Center (AMC) script. The opportunistic mode works for all files regardless how badly they are named, while strict mode works for reasonably well-named files and ignore files that cannot be matched accurately. See Match Mode for complete documentation.	opportunistic
#AMC_ARTWORK	When set to y, artwork is fetched and NFO file is generated by the Automated Media Center (AMC) script.	n
#AMC_LANG	Language used by the Automated Media Center (AMC) script to rename files. Two-characters language code or value like English, French, German, Chinese, etc can be used.	English
#AMC_MUSIC_FORMAT	Define how music files are renamed by the Automated Media Center (AMC) script. Filebot supports a very powerful naming scheme. See Format Expressions for complete documentation.	{plex}
#AMC_MOVIE_FORMAT	Define how movie files are renamed by the Automated Media Center (AMC) script. Filebot supports a very powerful naming scheme. See Format Expressions for complete documentation.	{plex}
#AMC_SERIES_FORMAT	Define how TV series files are renamed by the Automated Media Center (AMC) script. Filebot supports a very powerful naming scheme. See Format Expressions for complete documentation.	{plex}
#AMC_ANIME_FORMAT	Define how anime files are renamed by the Automated Media Center (AMC) script. Filebot supports a very powerful naming scheme. See Format Expressions for complete documentation.	{plex}
#AMC_PROCESS_MUSIC	When set to y, music files are processed by the Automated Media Center (AMC) script. A value of n does not process them.	y
#AMC_SUBTITLE_LANG	Comma-separated list of subtitle languages to download. Example: en,de,fr.	(no value)
#AMC_CUSTOM_OPTIONS	Custom arguments to pass to the Automated Media Center (AMC) script.	(no value)
#AMC_INPUT_DIR	Directory inside the container used as the input folder of the Automated Media Center (AMC) script.	/watch
#AMC_OUTPUT_DIR	Directory inside the container used as the output folder of the Automated Media Center (AMC) script.	/output
